WITH RECURSIVE FAMILY_TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT 자식.ID, 자식.PARENT_ID, 부모.GENERATION + 1
    FROM FAMILY_TREE 부모 JOIN ECOLI_DATA 자식 ON 부모.ID = 자식.PARENT_ID 
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM FAMILY_TREE

-- 자식 없는 애들 고르고
WHERE ID NOT IN (
    SELECT PARENT_ID
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
)

-- 세대별로 묶기
GROUP BY GENERATION
ORDER BY GENERATION;