-- 1. 0부터 23까지 숫자가 적힌 'TIME_TABLE'이라는 가짜 표를 만듭니다.
WITH RECURSIVE TIME_TABLE AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE WHERE HOUR < 23
)

-- 2. 이제 가짜 표(T)를 기준으로 진짜 표(A)를 LEFT JOIN으로 갖다 붙입니다.
SELECT T.HOUR, COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME_TABLE T
LEFT JOIN ANIMAL_OUTS A 
  ON T.HOUR = HOUR(A.DATETIME)
GROUP BY T.HOUR
ORDER BY T.HOUR ASC;