SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR,
    -- [핵심] 내 연도의 최댓값에서 내 크기를 바로 빼버림
    (MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY) AS YEAR_DEV,
    ID
FROM ECOLI_DATA
ORDER BY YEAR ASC, YEAR_DEV ASC;