SELECT
    CASE 
        WHEN SUM(S.NAME = 'Python') > 0 AND SUM(S.CATEGORY = 'Front end') > 0 THEN 'A'
        WHEN SUM(S.NAME = 'C#') > 0 THEN 'B'
        WHEN SUM(S.CATEGORY = 'Front end') > 0 THEN 'C'
    END AS GRADE,
    D.ID, D.EMAIL
FROM SKILLCODES S JOIN DEVELOPERS D ON (S.CODE & D.SKILL_CODE) = S.CODE
GROUP BY D.ID
HAVING GRADE IS NOT NULL
ORDER BY GRADE, D.ID
